# Generated by Django 4.2.16 on 2024-09-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=60, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unapproved", "Unapproved"),
                            ("approved", "Approved"),
                            ("banned", "Banned"),
                        ],
                        default="unapproved",
                        max_length=15,
                    ),
                ),
                ("registered", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
