# Generated by Django 4.2.16 on 2024-09-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_food", "0002_food_description_food_special_price_and_more"),
        ("app_general", "0002_subscription_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="food",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_food.food",
            ),
        ),
    ]
