# Generated by Django 4.2.16 on 2024-09-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_food", "0002_food_description_food_special_price_and_more"),
        ("app_general", "0003_alter_subscription_food"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="food",),
        migrations.AddField(
            model_name="subscription",
            name="food_set",
            field=models.ManyToManyField(to="app_food.food"),
        ),
    ]
