# Generated by Django 4.2.16 on 2024-10-02 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0003_food_image_relative_url_alter_food_description_and_more'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Like'), (2, 'Love'), (3, 'Insane')], default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_food_pivot_set', to='app_food.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_food_pivot_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_food_set',
            field=models.ManyToManyField(related_name='favorited_user_set', through='app_user.UserFavoriteFood', to='app_food.food'),
        ),
    ]
