# Generated by Django 4.2.16 on 2024-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_userfavoritefood_customuser_favorite_food_set'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfavoritefood',
            constraint=models.UniqueConstraint(fields=('user', 'food'), name='unique_user_food'),
        ),
    ]
